### ISSUE TITLE
Encountered unexpected multi-combat areas

### ISSUE THREAD

**Issue by HenningSte** [Nightfirecat/plugin-hub-plugins#56]
Error arises when teleporting in to gnome stronghold from wildy slayer cave using the seed pod.
Most likely not an actual error, but need to figure out how to stop this false alarm.

The plugin is not correct for the following areas:

* 2465, 3495

**Comment by Nightfirecat** [comment]
What version of the plugin are you running? This should have been fixed in #41

**Comment by HenningSte** [comment]
Not sure how to check the plugin version, but I have just tested this again after restarting my pc and runelite, and the issue persists.

Not sure if any of this matters, but to replicate the error I:
- teleported to Ferox
- entered the wildy slayer cave from the northern entrance
- use royal seed pod while standing in the middle of the greater demons right next to the entrance
- got the error after teleporting

RL Info panel:
RL version: 1.11.24.1
OS rev: 235
Launcher version: 2.6.7

**Comment by Nightfirecat** [comment]
Hmm, if you've restarted your computer, you should be on the latest version of the plugin also. I'll look into this further.

**Comment by Nightfirecat** [comment]
This is now fixed in aff67f9aa608b165de394ef7ccbb12ef9399e2f5, and deployed to the plugin hub as v1.4.3 in runelite/plugin-hub@0470fd98e3d8f4e6a6b1dc15ed2a93a21e1efd3b. You can get this update by either restarting your client or by updating the plugin directly in the 🔌 tab of the configuration panel. Thanks for the report!
